//
// Created by hrodic on 14/05/2026.
//

#ifndef CLASES_OBJETOS_Y_SOBRECARGAS_EMPRESA_H
#define CLASES_OBJETOS_Y_SOBRECARGAS_EMPRESA_H


class Empresa {
};


#endif //CLASES_OBJETOS_Y_SOBRECARGAS_EMPRESA_H
