//
// Created by hrodic on 14/05/2026.
//

#ifndef CLASES_OBJETOS_Y_SOBRECARGAS_INFRACCION_H
#define CLASES_OBJETOS_Y_SOBRECARGAS_INFRACCION_H


class Infraccion {
};


#endif //CLASES_OBJETOS_Y_SOBRECARGAS_INFRACCION_H
