//
// Created by hrodic on 10/05/2026.
//

#ifndef LAB07_PREG01_CLASES_LIBROPRESTADO_H
#define LAB07_PREG01_CLASES_LIBROPRESTADO_H


class LibroPrestado {
};


#endif //LAB07_PREG01_CLASES_LIBROPRESTADO_H
